{{- if and .Values.langfuse.enabled .Values.minio.createCredentialsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trace-pipeline.minioSecretName" . }}
  labels:
    {{- include "trace-pipeline.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser | quote }}
  root-password: {{ required "minio.rootPassword is required when minio.createCredentialsSecret is true" .Values.minio.rootPassword | quote }}
{{- end }}
